services:
  image_generator:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: image_generator
    image: sebastianwebapp/story_bang_image_generator:latest
    ports:
      - "4013:4013"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
