services:
  grok_text_generator:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: grok_text_generator
    image: sebastianwebapp/story_bang_grok_text_generator:latest
    ports:
      - "4014:4014"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
