services:
  read_story:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: read_story
    image: sebastianwebapp/story_bang_read_story:latest
    ports:
      - "4026:4026"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
