services:
  create_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: create_user
    image: sebastianwebapp/story_bang_create_user:latest
    ports:
      - "4004:4004"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
