services:
  read_id_story:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: read_id_story
    image: sebastianwebapp/story_bang_read_id_story:latest
    ports:
      - "4023:4023"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
