services:
  verify_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: verify_user
    image: sebastianwebapp/story_bang_verify_user:latest
    ports:
      - "4009:4009"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
