services:
  frontend:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: frontend
    image: sebastianwebapp/story_bang_frontend:latest
    ports:
      - "80:80"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
