services:
  read_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: read_user
    image: sebastianwebapp/story_bang_read_user:latest
    ports:
      - "4007:4007"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
