services:
  create_story:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: create_story
    image: sebastianwebapp/story_bang_create_story:latest
    ports:
      - "4022:4022"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
