services:
  update_character:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: update_character
    image: sebastianwebapp/story_bang_update_character:latest
    ports:
      - "4018:4018"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
