services:
  recover_password:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: recover_password
    image: sebastianwebapp/story_bang_recover_password:latest
    ports:
      - "4010:4010"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
