services:
  gptmedium:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: gptmedium
    image: sebastianwebapp/story_bang_gptmedium:latest
    ports:
      - "4021:4021"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
