services:
  grok_description_image:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: grok_description_image
    image: sebastianwebapp/story_bang_grok_description_image:latest
    ports:
      - "4015:4015"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
