services:
  delete_character:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: delete_character
    image: sebastianwebapp/story_bang_delete_character:latest
    ports:
      - "4017:4017"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
