services:
  deploy:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: deploy
    image: sebastianwebapp/story_bang_deploy:latest
    ports:
      - "3001:3001"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
