services:
  delete_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: delete_user
    image: sebastianwebapp/story_bang_delete_user:latest
    ports:
      - "4011:4011"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
