services:
  gpt2:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: gpt2
    image: sebastianwebapp/story_bang_gpt2:latest
    ports:
      - "4019:4019"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
