services:
  create_character:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: create_character
    image: sebastianwebapp/story_bang_create_character:latest
    ports:
      - "4016:4016"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
