services:
  whatsapp:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: whatsapp
    image: sebastianwebapp/story_bang_whatsapp:latest
    ports:
      - "4002:4002"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
