services:
  verification:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: verification
    image: sebastianwebapp/story_bang_verification:latest
    ports:
      - "4001:4001"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
