services:
  update_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: update_user
    image: sebastianwebapp/story_bang_update_user:latest
    ports:
      - "4008:4008"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
