services:
  messages_user:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: messages_user
    image: sebastianwebapp/story_bang_messages_user:latest
    ports:
      - "4003:4003"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
