services:
  delete_story:
    build:
      context: ./ # En donde se encuentra el archivo Dockerfile
    container_name: delete_story
    image: sebastianwebapp/story_bang_delete_story:latest
    ports:
      - "4025:4025"  # Mapea el puerto 3000
    restart: always # Reinicio del microservicio en caso de fallo
