name: StoryBang-Messages_User

on:
  push:
    branches:
      - QA
    paths:
      - 'Back/Messages_User/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Back/Messages_User

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # O ajusta a tu versión

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test  # o npx jest si no tienes "test" en package.json


      - name: Reemplazar nombre de imagen en docker-compose.yml
        run: |
          sed -i "s|^\s*image: .*|    image: sebastianwebapp/story_bang_messages_user_${{ secrets.IMAGE_TAG_QA }}|" docker-compose.yml


      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
          fi

          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          docker --version
          docker-compose --version

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images using Docker Compose
      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          # Verificar que las imágenes se enviaron correctamente
          echo "Verificando imágenes enviadas a DockerHub:"
          docker-compose -f docker-compose.yml images
