name: StoryBang-Mysql_Structure

on:
  push:
    branches:
      - QA  # Cambia según sea necesario
    paths:
      - 'Back/Login/Mysql_Structure/**'  # Solo activa el workflow si hay cambios en esta carpeta

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Back/Login/Mysql_Structure  # Todos los comandos correrán desde esta carpeta

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # O ajusta a tu versión

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test  # o npx jest si no tienes "test" en package.json


      - name: Reemplazar nombre de imagen en docker-compose.yml
        run: |
          sed -i "s|^\s*image: .*|    image: sebastianwebapp/story_bang_mysql_structure_${{ secrets.IMAGE_TAG_QA }}|" docker-compose.yml


      - name: Reemplazar valores en el archivo .env
        run: |
          sed -i "s|^MYSQL_HOST=.*|MYSQL_HOST=${{ secrets.MYSQL_HOST_QA }}|" .env

      # Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            echo "Docker no encontrado. Instalando..."
            sudo apt-get install -y docker.io
          else
            echo "Docker ya está instalado."
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose no encontrado. Instalando..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose ya está instalado."
          fi

          docker --version
          docker-compose --version

      # Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Asegúrate de que los secretos estén configurados
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images using Docker Compose
      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          # Verificar que las imágenes se enviaron correctamente
          echo "Verificando imágenes enviadas a DockerHub:"
          docker-compose -f docker-compose.yml images
