name: StoryBang-Translator

on:
  push:
    branches:
      - Prod
    paths:
      - 'Back/Translator/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Back/Translator

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Reemplazar valores en el archivo .env
        run: |
          sed -i "s/^CORS_ORIGIN=.*/CORS_ORIGIN=${{ secrets.CORS_ORIGIN_TRANSLATOR_QA }}/" .env
         



      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
          fi

          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          docker --version
          docker-compose --version

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images using Docker Compose
      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          # Verificar que las imágenes se enviaron correctamente
          echo "Verificando imágenes enviadas a DockerHub:"
          docker-compose -f docker-compose.yml images
